// ********RoostGPT********
/*
Test generated by RoostGPT for test golang-mini-projects_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test golang-mini-projects_clone using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=saveBooks_f944094c1b
ROOST_METHOD_SIG_HASH=saveBooks_1fdb6f7496

FUNCTION_DEF=func saveBooks(books [ // save books to books.json file
]Book) error
Scenario 1: Valid Scenario - Books are Saved Successfully

Details:
  Description: Checks if the provided book details are correctly saved in the 'books.json' file.
Execution:
  Arrange: Define an array of Book structs with valid data and a copy of that data as it should appear in the output file.
  Act: Invoke the target function with the Book array.
  Assert: Read the content of 'books.json' file and compare it with the expected output.
Validation:
  The assertion ensures that the target function is able to successfully save the given array of books. If the function performs correctly, the content of the 'books.json' file should match the expected JSON output. This test is important in relation to the application's requirement of saving books' details to a file.

Scenario 2: Error Scenario - File Cannot be Written

Details:
  Description: Checks what happens when the 'books.json' file cannot be written.
Execution:
  Arrange: Set up a permission scenario where the 'books.json' file cannot be written (such as disallowing write access to the file or containing it in a read-only directory). Prepare an array of Book structs with valid data.
  Act: Invoke the target function with the Book array.
  Assert: Check if an error is returned.
Validation:
  The assertion ensures that the function is able to handle situations when the file cannot be written. This test is significant as it checks how the function handles error scenarios.

Scenario 3: Error Scenario - JSON Cannot be Marshalled

Details:
  Description: Checks what happens when the provided books array cannot be marshalled to a JSON.
Execution:
  Arrange: Prepare a case where the Book array cannot be marshalled to JSON, for example, by putting in complex self-referencing structures that JSON doesn't support, or manipulate a Book struct to make it unserializable.
  Act: Invoke the target function with the manipulated Book array.
  Assert: Check if an error is returned.
Validation:
  This assertion checks if the function is able to handle situations where JSON marshalling fails. This test is crucial as it tests how the function handles such rare but potential error scenarios.
*/

// ********RoostGPT********

package bookstore

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"runtime/debug"
	"testing"
)

func TestSaveBooks(t *testing.T) {
	type args struct {
		books []Book
	}
	tests := []struct {
		name     string
		args     args
		success  bool
		hasError bool
		message  string
	}{
		{
			name: "Valid Scenario - Books are Saved Successfully",
			args: args{
				books: []Book{
					makeBook("1", "Go Programming", "Rob Pike", "50", "https://example.com/book.jpg"),
					makeBook("2", "Learning Go", "Caleb Doxsey", "60", "https://example.com/book2.jpg"),
				},
			},
			success:  true,
			hasError: false,
			message:  "expected successful execution of saveBooks",
		},
	}

	defer os.Remove("./books.json")

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered during test execution. %v\n%s", r, string(debug.Stack()))
					t.Fail()
				}
			}()
			if err := saveBooks(tt.args.books); (err != nil) != tt.hasError {
				t.Errorf("saveBooks() error = %v, expected to have error %v", err, tt.hasError)
			} else if !tt.hasError {
				data, _ := ioutil.ReadFile("./books.json")
				booksFromFile := make([]Book, 0)
				json.Unmarshal(data, &booksFromFile)
				if fmt.Sprint(tt.args.books) != fmt.Sprint(booksFromFile) {
					t.Errorf("data in JSON file does not match expected data")
				}
			}
			if (tt.success && tt.hasError) || (!tt.success && !tt.hasError) {
				t.Error("Test case setup error, both success and hasError can't be equal")
			}
		})
	}
}
func makeBook(id string, title string, author string, price string, imageUrl string) Book {
	return Book{id, title, author, price, imageUrl}
}
